name: CD

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions a tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macOS-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          key: ${{ secrets.SSH_KEY }}
          host: '143.244.185.46'
          username: root
          script: |
            git pull origin main
